# Generated by Django 5.0 on 2023-12-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restoranas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('adresas', models.CharField(max_length=200, verbose_name='Adresas')),
                ('telefonas', models.CharField(max_length=20, verbose_name='Telefonas')),
                ('el_pastas', models.EmailField(max_length=254, verbose_name='El. paštas')),
                ('atidarymo_valandos', models.TextField(verbose_name='Atidarymo valandos')),
            ],
        ),
    ]
