# Generated by Django 5.0 on 2023-12-06 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restoranai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darbuotojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=100, verbose_name='Vardas')),
                ('pareigos', models.CharField(max_length=100, verbose_name='Pareigos')),
                ('el_pastas', models.EmailField(max_length=254, verbose_name='El. paštas')),
                ('isdarbinimo_data', models.DateField(verbose_name='Įdarbinimo data')),
                ('restoranas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoranai.restoranas', verbose_name='Restoranas')),
            ],
        ),
    ]
