# Generated by Django 5.0 on 2023-12-06 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('darbuotojai', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stalas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeris', models.IntegerField(verbose_name='Numeris')),
                ('vietu_skaicius', models.IntegerField(verbose_name='Vietų skaičius')),
                ('uzsakymas', models.BooleanField(default=False, verbose_name='Užsakytas')),
                ('darbuotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stalai', to='darbuotojai.darbuotojas', verbose_name='Darbuotojas')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stalai', to='sales.sale', verbose_name='Salė')),
            ],
        ),
    ]
