# Generated by Django 5.0 on 2023-12-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalas',
            name='numeris',
            field=models.IntegerField(unique=True, verbose_name='Numeris'),
        ),
    ]
