# Generated by Django 5.0 on 2023-12-06 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restoranai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100)),
                ('talpa', models.IntegerField()),
                ('rezervuota', models.BooleanField(default=False)),
                ('restoranas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='restoranai.restoranas', verbose_name='Restoranas')),
            ],
        ),
    ]
